/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ChecklistItem = IDL.Record({
  'checked' : IDL.Bool,
  'text' : IDL.Text,
});
export const NoteContent = IDL.Record({
  'text' : IDL.Text,
  'isBold' : IDL.Bool,
  'isItalic' : IDL.Bool,
  'isHeading' : IDL.Bool,
  'isBulletPoint' : IDL.Bool,
  'checklistItems' : IDL.Opt(IDL.Vec(ChecklistItem)),
});
export const Progress = IDL.Variant({
  'belumMulai' : IDL.Null,
  'selesai' : IDL.Null,
  'sedangDikerjakan' : IDL.Null,
});
export const Category = IDL.Variant({
  'prioritas' : IDL.Null,
  'santai' : IDL.Null,
  'medium' : IDL.Null,
});
export const Time = IDL.Int;
export const Note = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'content' : IDL.Vec(NoteContent),
  'owner' : IDL.Principal,
  'dueDate' : IDL.Opt(Time),
  'progress' : Progress,
  'target' : IDL.Opt(IDL.Nat),
  'timestamp' : Time,
  'category' : Category,
  'images' : IDL.Vec(ExternalBlob),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addImageToNote' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checklistToggle' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createNote' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(NoteContent),
        IDL.Vec(ExternalBlob),
        Progress,
        Category,
        IDL.Opt(IDL.Nat),
        IDL.Opt(Time),
      ],
      [IDL.Text],
      [],
    ),
  'deleteNote' : IDL.Func([IDL.Text], [], []),
  'filterNotesByCategory' : IDL.Func([Category], [IDL.Vec(Note)], []),
  'filterNotesByProgress' : IDL.Func([Progress], [IDL.Vec(Note)], []),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getNote' : IDL.Func([IDL.Text], [Note], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateNote' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(NoteContent),
        IDL.Vec(ExternalBlob),
        Progress,
        Category,
        IDL.Opt(IDL.Nat),
        IDL.Opt(Time),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ChecklistItem = IDL.Record({ 'checked' : IDL.Bool, 'text' : IDL.Text });
  const NoteContent = IDL.Record({
    'text' : IDL.Text,
    'isBold' : IDL.Bool,
    'isItalic' : IDL.Bool,
    'isHeading' : IDL.Bool,
    'isBulletPoint' : IDL.Bool,
    'checklistItems' : IDL.Opt(IDL.Vec(ChecklistItem)),
  });
  const Progress = IDL.Variant({
    'belumMulai' : IDL.Null,
    'selesai' : IDL.Null,
    'sedangDikerjakan' : IDL.Null,
  });
  const Category = IDL.Variant({
    'prioritas' : IDL.Null,
    'santai' : IDL.Null,
    'medium' : IDL.Null,
  });
  const Time = IDL.Int;
  const Note = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'content' : IDL.Vec(NoteContent),
    'owner' : IDL.Principal,
    'dueDate' : IDL.Opt(Time),
    'progress' : Progress,
    'target' : IDL.Opt(IDL.Nat),
    'timestamp' : Time,
    'category' : Category,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addImageToNote' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checklistToggle' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createNote' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(NoteContent),
          IDL.Vec(ExternalBlob),
          Progress,
          Category,
          IDL.Opt(IDL.Nat),
          IDL.Opt(Time),
        ],
        [IDL.Text],
        [],
      ),
    'deleteNote' : IDL.Func([IDL.Text], [], []),
    'filterNotesByCategory' : IDL.Func([Category], [IDL.Vec(Note)], []),
    'filterNotesByProgress' : IDL.Func([Progress], [IDL.Vec(Note)], []),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getNote' : IDL.Func([IDL.Text], [Note], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateNote' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(NoteContent),
          IDL.Vec(ExternalBlob),
          Progress,
          Category,
          IDL.Opt(IDL.Nat),
          IDL.Opt(Time),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };